spring:
  application:
    name: manage-book
  datasource:
    url: jdbc:postgresql://localhost:5432/manage-book
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
server:
  port: 8080